version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: "k8s.io/api"
    - dependency-name: "k8s.io/apimachinery"
    - dependency-name: "k8s.io/client-go"

  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitor old release branches as well
  - package-ecosystem: "gomod"
    target-branch: "release/v0.12.x"
    labels: ["go", "dependencies", "release/v0.12.x"]
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    target-branch: "release/v0.11.x"
    labels: ["go", "dependencies", "release/v0.11.x"]
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    target-branch: "release/v0.10.x"
    labels: ["go", "dependencies", "release/v0.10.x"]
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    target-branch: "release/v0.9.x"
    labels: ["go", "dependencies", "release/v0.9.x"]
    directory: "/"
    schedule:
      interval: "weekly"
